version: '2'
services:

  postgres:
    image: postgres:9.4
    volumes:
      - ./psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'db_username'
      POSTGRES_PASSWORD: 'db_password'
      POSTGRES_DB: 'db_catalog'
    ports:
      - '5432:5432'