# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optionvalue',
            unique_together=set([('option_group', 'name')]),
        ),
    ]
