# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 19:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180602_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
